creating route to add manufacturer
hebertsanto/subway-gateway pull request #6
Opened 2024-08-22 13:59 UTC by hebertsanto

**Description**

creating route, services and repositories to add manufacturer

[**Trello Item**](https://trello.com/c/PTxTmdfy/3-feature-manufacturer)

More information:

- ⁠[Trello Project](https://trello.com/b/0boaadI6/subway-routes-hebert)

2024-08-22 18:09 UTC, Luiz-Cruz commented on src/controllers/manufacturer.ts
> +
Tem como fazer essa validação ser um middleware?

2024-08-22 18:11 UTC, Luiz-Cruz commented on src/controllers/manufacturer.ts
> +export class CreateManufacturerController implements Controller {
Tem como fazer essa controller vir de uma factory?

2024-08-22 18:13 UTC, Luiz-Cruz commented on src/controllers/manufacturer.ts
> +      const data = manufacturerSchemaValidation.parse(
A validação do schema (manufacturerSchemaValidation.parse) está sendo feita no controlador. Uma alternativa seria delegar essa responsabilidade a um middleware ou ao próprio serviço, para manter o controlador ainda mais simples.

2024-08-23 03:00 UTC, Luiz-Cruz commented on src/controllers/manufacturer.ts
> +);
Porque tem esse export const e lá em cima do arquivo tem um export class?

2024-08-23 03:03 UTC, Luiz-Cruz commented on src/logging/logger.ts
> +export const loggerService = new LoggerService();
porque não executou um export class lá em cima e decidiu fazer um export const aqui embaixo?

2024-08-23 03:04 UTC, Luiz-Cruz commented on src/routes/manufacturer.ts
> +  const httpResponse = await createManufacturerHandler.handle(req);
tem como mandar pra dentro desse handle só o que vai ser utilizado lá dentro? assim evita de ele ter que lidar com o objeto request do express, a não ser que seja necessário, é claro..

2024-08-23 03:15 UTC, Luiz-Cruz commented on src/services/manufacturer.ts
> +export interface IManufacturerService {
Tem como não usar o pattern service?

2024-08-23 03:16 UTC, Luiz-Cruz commented on src/services/manufacturer.ts
> +export class CreateManufacturerService implements IManufacturerService {
https://dev.to/asouza/service-o-pattern-que-virou-anti-pattern-568f

2024-08-23 14:46 UTC, Luiz-Cruz commented on src/infra/database/prisma.ts
> +export const prisma = new PrismaClient();
falta uma linha vazia no final do arquivo
https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2024-08-23 14:48 UTC, Luiz-Cruz commented on src/infra/factory/createManufacturerFactory.ts
> +export class CreateManufacturerFactory {
é uma factory de controller? seria bom deixar explícito no nome da classe

2024-08-23 14:48 UTC, Luiz-Cruz commented on src/infra/factory/createManufacturerFactory.ts
> +
remover linha vazia

2024-08-23 14:48 UTC, Luiz-Cruz commented on src/infra/factory/createManufacturerFactory.ts
> +export class CreateManufacturerFactory {
export sendo usado desnecessariamente

2024-08-23 14:49 UTC, Luiz-Cruz commented on src/infra/logging/logger.ts
> +export class LoggerService implements ILogger {
export

2024-08-23 14:50 UTC, Luiz-Cruz commented on src/presentation/controllers/manufacturer.ts
> +  constructor(readonly manufacturerService: IManufacturerUseCase) {}
`constructor(readonly addManufacturerUserCase: IManufacturerUseCase) {}`

2024-08-23 14:52 UTC, Luiz-Cruz commented on src/presentation/controllers/manufacturer.ts
> +  constructor(readonly manufacturerService: IManufacturerUseCase) {}
constructor(readonly addManufacturerUserCase: IAddManufacturerUseCase) {}

2024-08-23 14:52 UTC, Luiz-Cruz commented on src/presentation/controllers/manufacturer.ts
> +  constructor(readonly manufacturerService: IManufacturerUseCase) {}
`constructor(readonly addManufacturerUserCase: IAddManufacturerUseCase) {}`

2024-08-23 14:54 UTC, Luiz-Cruz commented on src/presentation/routes/manufacturer.ts
> +
remover linha vazia

2024-08-23 14:55 UTC, Luiz-Cruz commented on src/presentation/routes/manufacturer.ts
> +
linha vazia

2024-08-23 14:58 UTC, Luiz-Cruz commented on src/presentation/routes/manufacturer.ts
> +  new DataValidator(manufacturerSchemaValidation).validate(),
tem como esse middleware ser uma classe sua e não uma dependência direta do ZOD?

2024-08-23 15:00 UTC, Luiz-Cruz commented on src/application/errors/errors.ts
> +}
falta uma linha vazia no final do arquivo

2024-08-23 16:49 UTC, Luiz-Cruz commented on src/application/usecases/manufacturer.ts
> +export class CreateManufacturerUseCase implements IAddManufacturerUseCase {
Tenta usar um padrão de nomenclatura, vai ser create ou add?

`export class CreateManufacturerUseCase implements ICreateManufacturerUseCase`
ou
`export class AddManufacturerUseCase implements IAddManufacturerUseCase`

2024-08-23 17:08 UTC, Luiz-Cruz commented on src/infra/factory/createManufacturerFactory.ts
> +class CreateManufacturerFactoryController {
acredito que o uso de classe aqui ta sendo um pouco over, poderiamos fazer algo como:

```
export const createManufacturerController = (): CreateManufacturerController => {
  const manufacturerRepository = new ManufacturerRepository();
  const loggerService = new LoggerService();
  
  const createManufacturerUseCase = new CreateManufacturerUseCase(
    manufacturerRepository,
    loggerService
  );

  return new CreateManufacturerController(createManufacturerUseCase);
};
```

não vejo um ganho em usar classe aqui

2024-08-23 17:10 UTC, Luiz-Cruz commented on src/presentation/controllers/manufacturer.ts
> +export class CreateManufacturerController implements Controller {
o mesmo aqui sobre classes

2024-08-24 20:53 UTC, Luiz-Cruz requested changes
comentarios acima

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/infra/repositories/manufacturer.ts
> +};
Tem como isso fazer parte da camada de entidades e não da repository?

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/infra/repositories/manufacturer.ts
> +  manufacturer: ManufacturerCreateInput;
o mesmo aqui

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/infra/factory/controllers/add-manufacturer-controller-factory.ts
> +};
linha vazia no fim do arquivo

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/infra/repositories/manufacturer.ts
> +export type ManufacturerCreateInput = {
tem como trazer isso pra dentro de entities?

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/presentation/routes/manufacturer.ts
> +  new DataValidator(new ZodValidator(manufacturerSchemaValidation)).validate(),
não acho tão legivel termos 2 new dessa forma no validador da request, poderiamos implementar algo como esse exemplo abaixo?

[link](https://github.com/rmanguinho/clean-ts-api/blob/db12990a7b6e4b478074ade9cd89b2e539ad3931/src/main/routes/survey-result-routes.ts#L8)

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/presentation/routes/manufacturer.ts
> +
!

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/presentation/routes/manufacturer.ts
> +
!

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/infra/factory/usecases/add-manufacturer-factory.ts
> +export const makeDbAddManufacturer = (): AddManufacturerUseCase => {
```suggestion
export const makeDbAddManufacturer = (): AddManufacturerUseCase => {
```

Aqui você está gerando acoplamento entre o caso de uso e a implementação, o ideal seria isso ser uma interface

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/infra/factory/usecases/add-manufacturer-factory.ts
> +export const makeDbAddManufacturer = (): AddManufacturerUseCase => {
Você poderia tbm criar uma pasta só para essas factories, da controller e também dos use cases

2024-08-24 20:53 UTC, Luiz-Cruz commented on src/infra/factory/usecases/add-manufacturer-factory.ts
> +export const makeDbAddManufacturer = (): AddManufacturerUseCase => {
[exemplo](https://github.com/rmanguinho/clean-ts-api/blob/db12990a7b6e4b478074ade9cd89b2e539ad3931/src/main/factories)

2024-08-25 14:30 UTC, Luiz-Cruz commented on src/presentation/middlewares/zod-error.ts
> +export class DataValidator<T> {
Como você está usando essa classe só aqui nesse mesmo arquivo, talvez não precise dar um export nela.

2024-08-25 14:34 UTC, Luiz-Cruz commented on src/infra/factory/controllers/add-manufacturer-controller-factory.ts
> +export const makeAddManufacturerController = (): Controller => {
`export const makeAddManufacturerController = (): IController`

2024-08-25 15:19 UTC, Luiz-Cruz requested changes
falta os testes agora

2024-09-05 16:18 UTC, Luiz-Cruz requested changes
De modo geral, estão faltando alguns casos de teste. Por exemplo, deve-se validar falhas em Bad Request nos campos obrigatórios da requisição, tratar casos de CEP ou telefone inválidos por diversos motivos, lidar com caracteres inadequados ou até mesmo com o body da requisição não conforme o esperado. Isso se aplica tanto a testes unitários quanto de integração. Sugiro adicionar testes para cobrir esses casos específicos que podem ocorrer durante o ciclo de vida da requisição, tanto erros no db quanto erros diversos durante a request.

2024-09-05 16:18 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +
delete

2024-09-05 16:18 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +
delete

2024-09-05 16:18 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +
delete

2024-09-05 16:18 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +
delete

2024-09-05 16:18 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +
delete

2024-09-05 16:18 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +  it("should throw an error if creating manufacturer fails", async () => {
aqui ta faltando uma descrição mais nitida do porque falharia a request para esse usecase,
qual seria o motivo da falha?

2024-09-27 13:33 UTC, Luiz-Cruz commented on prisma/migrations/20240821025510_new_fields_in_manufacturers/migration.sql
> +ADD COLUMN     "updateAt" TIMESTAMP(3) NOT NULL;
updateAt -> updatedAt

nesse caso, como a migration ainda não subiu para prod ou develop, você poderia apagar localmente a versão que tem do manufacturer e gerar uma correta desde o inicio, assim não precisaria ter duas migrations separadas e sendo uma delas só para essa coluna updatedAt

2024-09-27 13:33 UTC, Luiz-Cruz commented on src/application/errors/errors.ts
> +    this.message = message;
creio que essa linha não seja necessária, talvez passar o message para o super(message) funcionaria, consegue testar por favor?

2024-09-27 13:33 UTC, Luiz-Cruz commented on src/application/errors/errors.ts
> +    this.message = message;
o mesmo aqui, consegue testar para validar?

2024-09-27 13:33 UTC, Luiz-Cruz commented on src/infra/logging/logger.ts
> +
uma linha somente ao final

2024-09-27 13:33 UTC, Luiz-Cruz commented on src/presentation/controllers/manufacturer.ts
> +      const data = request.body as Manufacturer;
talvez algo como:

```suggestion
      const data = request.body as ManufacturerRequest;
```

o que acha?

2024-09-27 13:33 UTC, Luiz-Cruz commented on src/presentation/controllers/manufacturer.ts
> +      const data = request.body as Manufacturer;
ou ManufacturerBody

2024-09-27 13:33 UTC, Luiz-Cruz commented on src/infra/repositories/manufacturer.ts
> +    const manufacturer = await prisma.manufacturer.create({
creio que você não precisaria criar essa classe só para conseguir fazer o teste, daria para gerar um mock dentro do teste e fazer as mesmas validações

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    expect(manufacturerRepositorySpy.createParams).toEqual(input);
a classe manufacturerRepositorySpy não interage com a lógica interna verdadeira do repositório, o mais adequado para esse teste seria um mock

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    expect(manufacturerRepositorySpy.createParams).toEqual(input);
a classe manufacturerRepositorySpy está incorreta em termos de conceito. A classe deveria estar sendo chamada de mock e não spy, porque ela não está espiando um método real existente; em vez disso, ela está substituindo ou simulando o comportamento do repositório.

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    expect(manufacturerRepositorySpy.createParams).toEqual(input);
Spy: Espia métodos ou funções reais, permitindo que você verifique quantas vezes foram chamadas, com quais argumentos, e o que retornaram, sem alterar o comportamento real.

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    expect(manufacturerRepositorySpy.createParams).toEqual(input);
Mock: Substitui completamente o comportamento do método ou função, permitindo que você controle os retornos e verifique as interações, sem depender da implementação real

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +});
o mesmo para esse teste aqui

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    const manufacturerData = {
```suggestion
    const manufacturerRequestBody = {
```
ou simplesmente

```suggestion
    const input = {
```

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +  it("Should create a manufacturer with valid data", async () => {
seria interessante usar um banco somente para testes

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +  it("Should create a manufacturer with valid data", async () => {
tipo um SQLite

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    const incompleteData = {
linha entre

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/infra/logging/logger.ts
> +export class LoggerSpy implements ILogger {
você não esta usando ele em nenhum lugar

2024-09-27 13:33 UTC, Luiz-Cruz commented on tests/infra/repositories/manufacturer.ts
> +export class ManufacturerRepositorySpy implements IManufacturerRepository {
creio que essa classe possa ser substituida por um mock direto no próprio teste

2024-09-27 13:33 UTC, Luiz-Cruz commented on .gitignore
> +combined.log
quem gera esses arquivos ou diretórios?

2024-09-29 01:56 UTC, hebertzin commented on .gitignore
> +combined.log
o winston

2024-09-29 01:57 UTC, hebertzin commented on tests/infra/repositories/manufacturer.ts
> +export class ManufacturerRepositorySpy implements IManufacturerRepository {
feito

2024-09-29 01:57 UTC, hebertzin commented on tests/infra/logging/logger.ts
> +export class LoggerSpy implements ILogger {
removido

2024-09-29 01:57 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    const incompleteData = {
feito

2024-09-29 02:02 UTC, hebertzin commented on src/presentation/controllers/manufacturer.ts
> +      const data = request.body as Manufacturer;
Acredito que essa alteração não seja vantajosa, pois estamos utilizando esse tipo em várias partes do projeto, inclusive como tipo de retorno em diversos métodos. Implementar essa mudança pode aumentar a complexidade do sistema sem uma necessidade real. Por exemplo, atualmente usamos `const data = request.body as Manufacturer`, e a proposta é mudar para `const data = request.body as ManufacturerRequest`; essa alteração só faria sentido se fosse somente utilizado no controller.

2024-09-29 02:02 UTC, hebertzin commented on src/infra/logging/logger.ts
> +
feito

2024-09-29 02:06 UTC, hebertzin commented on src/application/errors/errors.ts
> +    this.message = message;
feito

2024-09-29 02:06 UTC, hebertzin commented on src/application/errors/errors.ts
> +    this.message = message;
feito

2024-09-29 04:12 UTC, hebertzin commented on prisma/migrations/20240821025510_new_fields_in_manufacturers/migration.sql
> +ADD COLUMN     "updateAt" TIMESTAMP(3) NOT NULL;
feito

2024-09-29 14:15 UTC, Luiz-Cruz requested changes
talvez adicionar um .env.example de teste e de prod igual o que você tem ai?
só que com valores vazios obviamente

2024-09-29 14:15 UTC, Luiz-Cruz commented on prisma/migrations/20240929041148_renaming_fields_in_some_tables/migration.sql
> +ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL;
as migrations do manufacturer não estão na branch develop, logo, faz mais sentido vc deletar essas extras que você criou e gerar uma correta desde o inicio

2024-09-29 14:15 UTC, Luiz-Cruz commented on prisma/migrations/20240929041148_renaming_fields_in_some_tables/migration.sql
> +ALTER TABLE "Roles" DROP COLUMN "createAt",
aqui ta ok, como roles ja esta na develop não tem como deletar

2024-09-29 14:15 UTC, Luiz-Cruz commented on prisma/migrations/20240929041148_renaming_fields_in_some_tables/migration.sql
> +ALTER TABLE "Users" DROP COLUMN "updateAt",
aqui ta ok, como users ja esta na develop não tem como deletar

2024-09-29 14:15 UTC, Luiz-Cruz commented on src/adapters/express-router-adapter.ts
> +};
adicionar linha vazia ao final do arquivo

2024-09-29 14:15 UTC, Luiz-Cruz commented on src/presentation/middlewares/zod-validator-middleware.ts
> +
apenas uma linha ao final

2024-09-29 14:15 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    );
```suggestion
    manufacturerRepositoryMock.create.mockRejectedValueOnce(
      new Error("Simulated create error";)
    );
```

2024-09-29 14:15 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    await expect(sut.execute(input)).rejects.toThrow(AppError);
tem como validar o retorno?

teoricamente o erro retornado sempre seria o :

```
throw new AppError(
        "An error occurred while trying to create a manufacturer",
        HttpStatusCode.InternalServerError
      );
```

não?

2024-09-29 14:15 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    );
esse retorno não precisa validar, ta td ok

2024-09-29 14:15 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    const incompleteData = {
uma linha entre

2024-09-29 14:15 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    const incompleteData = {
uma linha entre

2024-09-29 14:15 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    expect(response.body.data).toHaveProperty("body");
tem como fazer uma validação única para tudo isso?
talvez colocar um objeto que response esperado e comparar com o retorno da request, o que acha? assim diminuimos a quantidade de "toHaveProperty"

2024-09-29 14:15 UTC, Luiz-Cruz commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +      expect.arrayContaining([
talvez o mesmo comentario que fiz para o teste acima possa ser válido para todos os outros cases,
os testes estão ok, talvez eu só tentaria remover a quantidade de expects e tentar acumular eles em um único
se possivel,

2024-09-29 14:30 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +      expect.arrayContaining([
feito

2024-09-29 14:30 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    expect(response.body.data).toHaveProperty("body");
feito

2024-09-29 14:30 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    const incompleteData = {
feito

2024-09-29 15:02 UTC, Luiz-Cruz requested changes

2024-09-29 15:02 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    expect(manufacturerRepositoryMock.create).toHaveBeenCalledWith(input);
vamos simular a sequencia que ocorre o teste, primeiro que ele seja chamado com o valor esperado
e por fim que retorne o esperado, só alterando a sequência:

```suggestion
    expect(manufacturerRepositoryMock.create).toHaveBeenCalledWith(input);
    expect(result).toEqual(resultManufacturer);
```

2024-09-29 15:02 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    );
faltou aqui

2024-09-29 15:02 UTC, Luiz-Cruz commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    );
```
manufacturerRepositoryMock.create.mockRejectedValueOnce(  
      new Error("Simulated create error";)  
    );  
```

2024-09-29 15:09 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    expect(Array.isArray(response.body.details)).toBe(true);
feito

2024-09-29 15:09 UTC, hebertzin commented on tests/application/usecases/manufacturer/manufacturer.spec.ts
> +    expect(manufacturerRepositoryMock.create).toHaveBeenCalledWith(input);
perfeito

2024-09-29 15:10 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    expect(Array.isArray(response.body.details)).toBe(true);
feito

2024-09-29 15:10 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    expect(Array.isArray(response.body.details)).toBe(true);
feito

2024-09-29 15:10 UTC, hebertzin commented on tests/e2e/manufacturer/manufacturer.spec.ts
> +    expect(Array.isArray(response.body.details)).toBe(true);
feito

2024-09-29 15:41 UTC, Luiz-Cruz approved these changes
Lgtm

2024-09-29 15:46 UTC, merged